"""Post-generation verification.

The generator is asked to be honest. This module assumes it was not.

Four checks run on every answer, cheapest first, and any one of them can
demote the turn to a caveat or an escalation:

1. **Citation validity** (deterministic). Every id the answer cites must be a
   document that was actually retrieved for this turn. A model that cites
   `[POLICY-11]` when no such document exists is hallucinating in the most
   detectable way available, and this check is free.

2. **Retired-claim leakage** (deterministic). POLICY-02 contains the sentence
   "Older help-center documentation referenced a 7-day refund period". A model
   that answers "you have 7 days" is quoting real retrieved text and will
   therefore pass any naive groundedness check. This check looks for the
   salient tokens of each quarantined claim appearing in the answer *without*
   a nearby retirement marker.

3. **Safety** (deterministic). The answer must never solicit a full card
   number, CVV, PIN or password — POLICY-07 and POLICY-10 are explicit, and
   POLICY-10 records that an internal instruction to ask for card digits was
   retired.

4. **Groundedness** (LLM judge). The answer is decomposed into atomic claims
   and each is checked for entailment against the passages. This is the
   expensive check and the only one that needs a model, so it runs last.

Why a separate judge call rather than trusting `self_confidence`: a model's
stated confidence in its own output is close to useless as a hallucination
signal — it is generated by the same forward pass that produced the error.
Re-reading the answer against the sources as a fresh task, with no obligation
to defend it, catches materially more. The judge is not free of correlated
blind spots, which is why the two deterministic checks above can fail an
answer on their own.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from app.config import Settings, settings
from app.generator import Generation, format_context
from app.providers.base import LLM, LLMError
from app.retrieval import RetrievalResult

# Words that mark a statement as historical rather than current. If one of
# these sits near a retired claim's tokens, the answer is describing the past
# correctly rather than asserting it.
_RETIREMENT_MARKERS = re.compile(
    r"\b(no longer|used to|previously|outdated|obsolete|former(?:ly)?|"
    r"withdrawn|retired|archived|older|superseded|has changed|not current|"
    r"was replaced|replaced by|historic(?:al)?)\b",
    re.I,
)
_MARKER_WINDOW = 160

# Requests for secrets the assistant must never make.
_UNSAFE_REQUEST = re.compile(
    r"\b(?:provide|send|share|give|enter|confirm|tell)\b[^.?!]{0,60}\b"
    r"(?:full card number|card number|cvv|cvc|security code|pin|password|"
    r"authentication code|one-time code)\b",
    re.I,
)

_SALIENT = re.compile(r"\b(\d{1,3})[-\s]?(day|days|user|users|quiz|quizzes|month|months)\b", re.I)
_PROPER_NOUN = re.compile(r"\b(?:Internet Explorer|cellular data|five-user family plan)\b", re.I)

_CITE_IN_TEXT = re.compile(r"\[([A-Z]+-\d+)\]")


@dataclass
class Verification:
    groundedness: float = 1.0
    invalid_citations: list[str] = field(default_factory=list)
    uncited: bool = False
    retired_claim_leaks: list[str] = field(default_factory=list)
    unsafe_request: bool = False
    unsupported_claims: list[str] = field(default_factory=list)
    judge_ran: bool = False
    notes: list[str] = field(default_factory=list)

    @property
    def hard_failure(self) -> bool:
        """Failures that make the answer unusable regardless of its score."""
        return bool(self.invalid_citations) or bool(self.retired_claim_leaks) or self.unsafe_request

    def reason_codes(self) -> list[str]:
        codes: list[str] = []
        if self.invalid_citations:
            codes.append("invalid_citation")
        if self.retired_claim_leaks:
            codes.append("retired_claim_leak")
        if self.unsafe_request:
            codes.append("unsafe_information_request")
        if self.uncited:
            codes.append("uncited_answer")
        if self.judge_ran and self.unsupported_claims:
            codes.append("unsupported_claims")
        return codes

    def as_dict(self) -> dict[str, Any]:
        return {
            "groundedness": round(self.groundedness, 3),
            "invalid_citations": self.invalid_citations,
            "uncited": self.uncited,
            "retired_claim_leaks": self.retired_claim_leaks,
            "unsafe_request": self.unsafe_request,
            "unsupported_claims": self.unsupported_claims,
            "judge_ran": self.judge_ran,
            "notes": self.notes,
        }


class Verifier:
    def __init__(self, llm: LLM, cfg: Settings | None = None) -> None:
        self.llm = llm
        self.cfg = cfg or settings

    # ------------------------------------------------------------------
    def verify(self, generation: Generation, retrieval: RetrievalResult) -> Verification:
        result = Verification()
        answer = generation.answer or ""
        if not answer.strip():
            result.groundedness = 0.0
            result.notes.append("empty answer")
            return result

        available = set(retrieval.doc_ids)

        # 1. citation validity -----------------------------------------
        claimed = set(generation.citations) | set(_CITE_IN_TEXT.findall(answer))
        result.invalid_citations = sorted(c for c in claimed if c not in available)
        result.uncited = not claimed and _looks_factual(answer)

        # 2. retired-claim leakage -------------------------------------
        result.retired_claim_leaks = _find_retired_leaks(answer, retrieval.deprecated_claims)

        # 3. safety ----------------------------------------------------
        result.unsafe_request = bool(_UNSAFE_REQUEST.search(answer))

        # 4. groundedness judge ----------------------------------------
        if self.cfg.enable_verifier and self.llm.is_live:
            judged = self._judge(answer, retrieval)
            if judged is not None:
                result.groundedness, result.unsupported_claims = judged
                result.judge_ran = True
            else:
                result.notes.append("judge unavailable; groundedness not verified")
                result.groundedness = 0.5
        elif not self.llm.is_live:
            # Offline extractive answers are verbatim source text, so they are
            # grounded by construction — but they are also not real answers, so
            # we keep the score below the gate to force a caveat.
            result.groundedness = 0.5
            result.notes.append("offline mode: groundedness not verified")

        # Deterministic failures override a generous judge.
        if result.hard_failure:
            result.groundedness = min(result.groundedness, 0.25)
        return result

    # ------------------------------------------------------------------
    def _judge(
        self, answer: str, retrieval: RetrievalResult
    ) -> tuple[float, list[str]] | None:
        system = (
            "TASK: verify\n"
            "You are a strict factuality checker for a customer-support assistant.\n"
            "You are given SOURCES and a draft ANSWER. Split the answer into atomic factual "
            "claims and decide, for each, whether the SOURCES entail it.\n"
            "Rules:\n"
            "- Judge only support: is this claim stated or directly implied by the sources? "
            "Do not judge style, helpfulness or whether it is good advice.\n"
            "- Generic conversational filler, offers to help and clarifying questions are not "
            "factual claims; ignore them.\n"
            "- A claim that a source has *withdrawn* or marked outdated is NOT supported if the "
            "answer presents it as currently true.\n"
            "- Hedged statements ('may', 'generally', 'in most cases') are supported if the "
            "source hedges the same way.\n"
            'Reply with JSON only: {"supported": ["..."], "unsupported": ["..."], '
            '"groundedness": 0.0}  where groundedness = supported / (supported + unsupported).'
        )
        user = (
            f"SOURCES:\n{format_context(retrieval.candidates)}\n\n"
            f"ANSWER:\n{answer}"
        )
        try:
            data = self.llm.complete_json(system, user, temperature=0.0, max_tokens=800)
        except (LLMError, TypeError):
            return None

        supported = [str(x) for x in data.get("supported") or []]
        unsupported = [str(x) for x in data.get("unsupported") or []]
        total = len(supported) + len(unsupported)

        # Recompute rather than trusting the model's own arithmetic; models
        # routinely report a groundedness that does not match the lists they
        # just produced.
        if total:
            score = len(supported) / total
        else:
            score = _as_float(data.get("groundedness"), default=0.5)
        return max(0.0, min(1.0, score)), unsupported


# ---------------------------------------------------------------------------
# deterministic helpers
# ---------------------------------------------------------------------------


def _find_retired_leaks(answer: str, deprecated_claims: list[dict[str, Any]]) -> list[str]:
    """Detect a withdrawn statement being presented as current.

    We look for the claim's *salient* tokens — the numbers-with-units and the
    handful of named things that make a retired rule identifiable ("7 days",
    "five quizzes", "Internet Explorer") — rather than matching the sentence,
    because the model paraphrases. A hit only counts if there is no retirement
    marker nearby, so "LearnForge no longer treats the 7-day period as
    current" passes while "you have 7 days to request a refund" does not.
    """
    leaks: list[str] = []
    for claim in deprecated_claims:
        text = claim.get("claim_text", "")
        tokens = {f"{m.group(1)} {m.group(2).lower()}" for m in _SALIENT.finditer(text)}
        tokens |= {m.group(0).lower() for m in _PROPER_NOUN.finditer(text)}
        for token in tokens:
            for position in _find_token(answer, token):
                window = answer[
                    max(0, position - _MARKER_WINDOW) : position + _MARKER_WINDOW
                ]
                if not _RETIREMENT_MARKERS.search(window):
                    leaks.append(f"{claim['doc_id']}: '{token}' asserted as current")
                    break
            else:
                continue
            break
    return sorted(set(leaks))


def _find_token(answer: str, token: str) -> list[int]:
    """Positions of a '<number> <unit>' or phrase token, allowing '7-day'."""
    parts = token.split(" ", 1)
    if len(parts) == 2 and parts[0].isdigit():
        number, unit = parts
        pattern = rf"\b{re.escape(number)}[-\s]?{re.escape(unit.rstrip('s'))}s?\b"
    else:
        pattern = re.escape(token)
    return [m.start() for m in re.finditer(pattern, answer, re.I)]


def _looks_factual(answer: str) -> bool:
    """Does this answer make claims that ought to be cited?

    A pure clarifying question or a handoff message has nothing to cite, and
    flagging it as uncited would punish exactly the behaviour we want.
    """
    stripped = answer.strip()
    if stripped.endswith("?") and len(stripped.split()) < 40:
        return False
    return len(stripped.split()) > 15


def _as_float(value: Any, *, default: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default
